# Generated by Django 2.2.1 on 2019-10-02 05:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import starter_kit.models
import starter_kit.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestNumber', models.CharField(default=starter_kit.models.requestNumGenerator, max_length=200, unique=True)),
                ('patient_num', models.CharField(max_length=200)),
                ('requestDate', models.DateTimeField(default=datetime.datetime(2019, 10, 2, 5, 54, 6, 212561, tzinfo=utc))),
                ('medical_Image', models.ImageField(upload_to='medical', validators=[starter_kit.validators.validate_file_shape, starter_kit.validators.validate_file_extension])),
                ('processed', models.BooleanField(default=False)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('addedOn', models.DateTimeField(default=datetime.datetime(2019, 10, 2, 5, 54, 6, 212771, tzinfo=utc))),
                ('requestingPractitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patients data',
            },
        ),
    ]
