# Generated by Django 2.2.1 on 2019-10-03 02:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('starter_kit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='addedOn',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 2, 50, 43, 987941, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='medical_Image',
            field=models.ImageField(upload_to='medical'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='requestDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 2, 50, 43, 987719, tzinfo=utc)),
        ),
    ]
