# Generated by Django 2.2.1 on 2019-10-03 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('starter_kit', '0002_auto_20191003_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='pneumonia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='addedOn',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 11, 24, 42, 903926, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='requestDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 11, 24, 42, 903694, tzinfo=utc)),
        ),
    ]
